// Static-asset half of `npm run site`.
//
// The npm script esbuilds src/site/main.tsx to dist-site/bundle.js first; this
// script then assembles the rest of the deployable directory:
//
//   dist-site/index.html   copied from site/index.html
//   dist-site/manifest.webmanifest, dist-site/icons/
//                          the PWA half: installable from the phone's share
//                          sheet. Icons are generated by `npm run icons` and
//                          committed under site/icons/.
//   dist-site/sw.js        the service worker, with __BUILD_VERSION__ replaced
//                          by a hash of what was actually built — that string
//                          names the shell cache, so a deploy invalidates the
//                          previous one instead of serving a stale bundle
//                          forever
//   dist-site/narration/   copied from public/narration (the compositions load
//                          these via staticFile(), resolved relative to the
//                          page — so they must ship alongside index.html)
//   dist-site/backgrounds/ same, for the painted backdrops (public/backgrounds)
//                          — a missing plate is a blank world on the phone the
//                          episode is actually reviewed on
//   dist-site/.nojekyll    GitHub Pages: serve files/dirs as-is
//
// Node-only (no shell built-ins) so it works the same on Linux/macOS/Windows.

import { cp, mkdir, readFile, rm, writeFile, stat, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "dist-site");
const bundle = path.join(outDir, "bundle.js");
const narrationSrc = path.join(root, "public", "narration");
const narrationOut = path.join(outDir, "narration");
const backgroundsSrc = path.join(root, "public", "backgrounds");
const backgroundsOut = path.join(outDir, "backgrounds");

async function exists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

await mkdir(outDir, { recursive: true });

if (!(await exists(bundle))) {
  console.error(
    "dist-site/bundle.js is missing — run this via `npm run site` (esbuild step first).",
  );
  process.exit(1);
}

const indexSrc = path.join(root, "site", "index.html");
await cp(indexSrc, path.join(outDir, "index.html"));

// --- PWA: manifest, icons, versioned service worker -------------------------
//
// The version is a hash of the two files that actually change between deploys
// (the bundle and the shell). It becomes the service worker's cache name, so a
// new build always lands in a new cache and the old one is dropped on activate
// — without it, a phone that has installed the site would serve last month's
// bundle out of its cache indefinitely.
const manifestSrc = path.join(root, "site", "manifest.webmanifest");
if (await exists(manifestSrc)) {
  await cp(manifestSrc, path.join(outDir, "manifest.webmanifest"));
}

const iconsSrc = path.join(root, "site", "icons");
const iconsOut = path.join(outDir, "icons");
await rm(iconsOut, { recursive: true, force: true });
if (await exists(iconsSrc)) {
  await cp(iconsSrc, iconsOut, { recursive: true });
} else {
  console.warn(
    "site/icons not found — the site will install without an icon. Run `npm run icons`.",
  );
}

const swSrc = path.join(root, "site", "sw.js");
let version = "dev";
if (await exists(swSrc)) {
  const hash = createHash("sha256");
  hash.update(await readFile(bundle));
  hash.update(await readFile(indexSrc));
  version = hash.digest("hex").slice(0, 12);
  const worker = await readFile(swSrc, "utf8");
  if (!worker.includes("__BUILD_VERSION__")) {
    console.warn("site/sw.js has no __BUILD_VERSION__ placeholder to inject.");
  }
  await writeFile(
    path.join(outDir, "sw.js"),
    worker.replaceAll("__BUILD_VERSION__", version),
  );
}

// Replace rather than merge, so clips deleted from public/ don't linger.
await rm(narrationOut, { recursive: true, force: true });
if (await exists(narrationSrc)) {
  await cp(narrationSrc, narrationOut, {
    recursive: true,
    // Leave build bookkeeping (.cache.json) out of the published site.
    filter: (src) => !path.basename(src).startsWith("."),
  });
} else {
  console.warn(
    "public/narration not found — the site will play silent. Run `npm run narration`.",
  );
}

// Replace rather than merge, for the same reason as the narration above.
await rm(backgroundsOut, { recursive: true, force: true });
if (await exists(backgroundsSrc)) {
  await cp(backgroundsSrc, backgroundsOut, {
    recursive: true,
    filter: (src) => !path.basename(src).startsWith("."),
  });
} else {
  console.warn(
    "public/backgrounds not found — painted scenes will render empty. Run `npm run backgrounds`.",
  );
}

await writeFile(path.join(outDir, ".nojekyll"), "");

const { size } = await stat(bundle);
const slugs = (await exists(narrationOut))
  ? (await readdir(narrationOut, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  : [];
const bgSlugs = (await exists(backgroundsOut))
  ? (await readdir(backgroundsOut, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  : [];
const icons = (await exists(iconsOut))
  ? (await readdir(iconsOut)).filter((name) => !name.startsWith("."))
  : [];
console.log(
  `dist-site ready: bundle.js (${Math.round(size / 1024)} kB), index.html, .nojekyll` +
    `, sw.js@${version}, manifest.webmanifest` +
    (icons.length ? `, icons/{${icons.join(", ")}}` : "") +
    (slugs.length ? `, narration/{${slugs.join(", ")}}` : "") +
    (bgSlugs.length ? `, backgrounds/{${bgSlugs.join(", ")}}` : ""),
);
